Boot up restart
Cislunar-Explorers/FlightSoftware pull request #1
Opened 2020-10-26 23:17 UTC by jag527

Things that I changed on bootup_restart:
-Initialization/checking of cameras now utilizes the camera_mux/camera objects located in the Opnav branch (under OpticalNavigation/core/camera.py)
-Changed in db.py:
    -is_bootup is now a boolean as opposed to a string

Concerns:
-Not sure if the camera verification is taking place, specifically in restartmode
-Pretty sure the logging is right, but is the only place I should log in the db? or is there somewhere else?
-Imports

2020-10-27 05:02 UTC, tmf97 commented on flight_modes/restart_reboot.py
> +        time.sleep(60)
Replace 60 with BOOTUP_SEPERATION_DELAY from constants.py

2020-10-27 05:17 UTC, tmf97 commented on flight_modes/restart_reboot.py
> +
You'll need to import FlightMode from flight_mode here, and add an empty __init__.py file in this folder

2020-10-27 05:41 UTC, tmf97 requested changes
Solid start! I've requested a few changes - mostly to do with imports.
It'd be great if you could get this tested on the HITL before merging to master to iron out any issues that may arise - let me know if you need help setting that up.
I would double check the camera mux initialization and follow what already exists; you or Stephen know best on how to do this but make sure you know exactly what your code does before testing on the HITL.
There will be some more functionality that will need to be implemented (as described in [https://cornell.app.box.com/file/655915541214](https://cornell.app.box.com/file/655915541214)) later, but this is a good starting point.

2020-10-27 21:18 UTC, jag527 commented on flight_modes/restart_reboot.py
> +
What will be the purpose of the extra __init__.py?

2020-10-27 22:13 UTC, tmf97 commented on flight_modes/restart_reboot.py
> +
You'll need it in order to import the FlightSoftware class from the flight_mode.py file - the environment your IDE is in doesn't map perfectly to what's happening on the pi.

2020-10-29 00:19 UTC, sjz38 commented on flight_modes/restart_reboot.py
> +        assert mux.detect()
Here we need to use the output of detect  (True, False) to see if we need to do a reboot. Also, after we create the mux object we should call selectCamera so that a camera is chosen.

2020-10-29 00:19 UTC, sjz38 commented on flight_modes/restart_reboot.py
> +        cam = camera.Camera()
We should create a camera object here and catch any assertion it raises. Eventually, we would want to restart a limited number of times before giving up if we can't access the camera

2020-10-29 00:59 UTC, sjz38 requested changes

2020-10-29 00:59 UTC, sjz38 commented on flight_modes/restart_reboot.py
> +        super().run_mode(self)
You have to define a run_mode function in each flight mode class. In the main event loop, run_mode is automatically called for the flight mode that is currently active. Run_mode is where you specify what you want the flight mode to do - for instance, in bootup mode, you would want run_mode to init_camera (not init)

2020-10-30 03:50 UTC, jag527 commented on flight_modes/restart_reboot.py
> +        super().run_mode(self)
So how should I change this? Should I not be using super()?

2020-11-01 03:13 UTC, sjz38 commented on flight_modes/restart_reboot.py
> +        super().run_mode(self)
Yes. Each flight mode defines its own run_mode function because each mode has different functionality. This is where you specify exactly what commands you want to run. For instance, you call init_camera in __init__, but this should actually be called within run_mode. If you look at flight_mode.py, you'll see that the parent class FlightMode leaves the implementation of run_mode up to its subclasses. Also, it might help to look at main.py to see the general flow of how we plan to use flight modes

2020-11-01 03:43 UTC, sjz38 requested changes
Some general comments:
Make sure to log the times the Pi does not detect any cameras and needs to do a restart because of that.
For the restart_mode, is there some command you need to add to tell the hardware to do a reboot? Idk if it might be a Pi command you can look up online... perhaps @tmf97 would know.

2020-11-01 03:43 UTC, sjz38 commented on flight_modes/restart_reboot.py
> +        for x in range(1, 5):
Since bootup is intended to be only run at the beginning of the mission, it should be fine to just select one camera and leave it at that. For the cycling of cameras see my comment in the restart mode.

2020-11-01 03:43 UTC, sjz38 commented on flight_modes/restart_reboot.py
> +        assert camera.Camera()
I forgot to tell you that I made a Camera.initialize() function in camera.py that instantiates a PiCamera object that we can use to make sure the Pi is able to interface with the camera (I added camera.py to your branch too). Also, here you should select a camera first. When selecting, I think we should try to alternate which camera we select for each time we reboot.

2020-11-26 17:47 UTC, tmf97 approved these changes

2020-12-02 19:57 UTC, sjz38 commented on flight_modes/restart_reboot.py
> +        mux.selectCamera(random.choice([1, 2, 3]))
Maybe add a comment here saying that we need to select a camera before rebooting so that we will be able to detect a camera on reboot?

2020-12-02 20:00 UTC, sjz38 approved these changes

2020-12-02 20:34 UTC, merged