Maneuver fm
Cislunar-Explorers/FlightSoftware pull request #108
Opened 2021-10-23 16:03 UTC by mly32

### Summary

This PR addresses Jira ticket CISLUNAR-18.

Maneuver mode was updated to check for glow plug failure.

### Testing

Lacks testing at this stage.

### Notes

Is it possible to have the maneuver mode's initialization defined outside of `main`? It feels like it really belongs in maneuver_flightmode. Say I end up changing the queue type (e.g., I use a heap instead of python's default priority_queue class, or like in this PR where I changed it from a queue to a priority_queue). Ideally, none of the other functions/parts of the code would need to know, they would just use ManeuverMode().addEvent() or something similar. 

The queue and other data still are not saved onto disk in the event of a reboot. 

### Comments
- [x] I'm not sure why set_parameter uses kwargs and how to use the function defined in command_defintions. 
- [x] What is the behavior for when a scheduled burn time has already passed without maneuver mode running?
- [x] I left the constants as basic values, but they need to be updated.
- [x] My glowplug check logic and glowplug failure logics are basic and could use improvements.

2021-10-23 21:27 UTC, tmf97 submitted a review, later dismissed
Looks really really good - We talked about changing the maneuver queue to a list or something else - up to you on how to implement this.

2021-10-30 19:43 UTC, mly32 commented
Added (basic) tests using mocks. Fixed/updated maneuver mode and moved params into paramaters.py.

Failing the CI right now because I placed the new params in the wrong place.

2021-10-31 05:19 UTC, tmf97 requested changes
Almost there - all the logic/reasoning is perfect, just some implementation quirks need ironing out. Huge fan of the maneuver test!

2021-10-31 05:19 UTC, tmf97 commented on flight_modes/maneuver_flightmode.py
> +                self._parent.gom.glowplug(consts.GLOWPLUG_DURATION)
Oh, we should be using `parameters.GLOWPLUG_DURATION` instead of `constants...`, my bad for not seeing that earlier. 
The following should all be removed from constants.py, and used from parameters instead:
```
SPLIT_BURNWIRE_DURATION = 1  # second
ANTENNAE_BURNWIRE_DURATION = 1  # second
GLOWPLUG_DURATION = 1  # SECOND
BURN_WAIT_TIME = 15  # minutes
```

The reason for this is that it's very easy to change the values of parameters (there's a command where we can uplink a new value), but very hard to change the value of a parameter (we have to uplink a new `constants.py` file containing the new value, then restart the flight software) - it's doable, just much more involved.

2021-10-31 05:19 UTC, tmf97 commented on main.py
> +        self.maneuver_queue = PriorityQueue()
Weren't we talking about changing the maneuver_queue to a list?

2021-10-31 05:19 UTC, tmf97 commented on flight_modes/maneuver_flightmode.py
> +                # TODO ground msg?... do a final check?
I've thought about defining a set of "error codes" that we could collect and downlink on request. In this case we'd add something to the error code "queue" or something. Defining that is for another PR though, just keep the TODO for now.
Something we could do here is to try to increase the GLOWPLUG_DURATION, but I think that increase  would be best performed by ground operators.

2021-10-31 05:19 UTC, tmf97 commented on flight_modes/maneuver_flightmode.py
> +            smallest_time_burn = self._parent.maneuver_queue.get()
Remember that `queue.get()` removes the item from the queue as well as returning it - are you sure you want that here?

2021-10-31 05:19 UTC, tmf97 commented on flight_modes/maneuver_flightmode.py
> +        set_parameter("SCHEDULED_BURN_TIME", smallest_time_burn, False)  # for testing
Same comment as in command_definitions.py

2021-10-31 05:19 UTC, tmf97 commented on main.py
> +        self.maneuver_queue = PriorityQueue()
Huh, I learned a thing or two from https://stackoverflow.com/questions/9287919/can-i-get-an-item-from-a-priorityqueue-without-removing-it-yet

2021-10-31 05:19 UTC, tmf97 commented on utils/constants.py
> +PRESSURE_DELTA = -1
All these should be in parameters, not constants

2021-10-31 05:19 UTC, tmf97 commented on tests/maneuver_test.py
> +class FakeGOM():
This is something we'll eventually want to breakout into its own file, but good enough for now

2021-11-09 19:03 UTC, mly32 commented
constants need to be updated since there are still other variables that should be parameters such as `SPLIT_BURNWIRE_DURATION`.

I don't like using a string to set parameters as done here: `set_parameter("GLOWPLUG2_VALID", self.task_completed, consts.FOR_FLIGHT)`. I will look into a way to do this safely in another PR.

Will also look into removing parameters.json as part of the codebase. it should be something that is git-ignored and should be generated if the file does not exist

2021-11-09 22:28 UTC, tmf97 commented on tests/maneuver_test.py
> +        return 0
Really jank, but this worked on my machine:
```suggestion
class FakeGOM(Gomspace):

    def __init__(self):
        self.pc = None

    def glowplug(self, duration, delay=0):
        return None

    def glowplug2(self, duration, delay=0):
        return None
```

2021-11-12 03:15 UTC, tmf97 approved these changes
Looks solid! We should flatsat test this soon - how does this weekend work?

2021-11-13 00:43 UTC, mly32 commented
> Looks solid! We should flatsat test this soon - how does this weekend work?

Sounds like a plan!

2021-11-13 00:45 UTC, merged