Sk opnav db skeleton
Cislunar-Explorers/FlightSoftware pull request #115
Opened 2021-11-06 18:06 UTC by andxu282

### Summary

This PR addresses Jira ticket CISLUNAR-     

### Testing

### Notes

### Comments
- [ ] Add an x between the brackets if you commented your code well!

2021-11-06 20:02 UTC, tmf97 reviewed
FSW changes look good enough - some of the issues will get squashed by the merge (I hope)

2021-11-07 04:27 UTC, sjz38 commented on utils/parameters.py
> +EARTH_THRESH = ((0, 0, 0), (255, 30, 30))
Good point. I made these changes and I'll have Andrew run his algo again to make sure it still works

2021-11-07 04:27 UTC, sjz38 commented on main.py
> +from datetime import datetime, timedelta
Not applicable after master merge

2021-11-09 03:08 UTC, tmf97 commented
Github won't let you merge before fixing the 6 issues pyright is picking up - lmk if you need help resolving those.

Are any of the tests in OpticalNavigation/tests able to run on our CI? If so let's add them. If not, let's leave it for another PR

2021-11-10 14:09 UTC, tmf97 commented on OpticalNavigation/core/find_algos/find_with_hough_transform_and_contours.py
> +        u = np.linalg.inv(camera_params.cam3Rotation).dot(u)
This fixes the pyright error for me, replaces with a warning for "cam_u might be unbound", but I think that's acceptable
```suggestion
camNum = int(re.search(r"[cam](\d+)", src).group(1))
    assert camNum in [1, 2, 3], "Error in getting the camera number from filename"
    if camNum == 1:
        cam_DCM: np.ndarray = np.linalg.inv(camera_params.cam1Rotation)
        u_cam = cam_DCM.dot(u)
    elif camNum == 2:
        cam_DCM: np.ndarray = np.linalg.inv(camera_params.cam2Rotation)
        u_cam = cam_DCM.dot(u)
    elif camNum == 3:
        cam_DCM: np.ndarray = np.linalg.inv(camera_params.cam3Rotation)
        u_cam = cam_DCM.dot(u)
```

2021-11-10 15:38 UTC, sjz38 commented on OpticalNavigation/core/find_algos/find_with_hough_transform_and_contours.py
> +        u = np.linalg.inv(camera_params.cam3Rotation).dot(u)
Worked for me after changing np.array to np.ndarray in the class definition where u is

2021-11-10 21:48 UTC, sjz38 commented on utils/parameters.py
> +EARTH_THRESH = ((0, 0, 0), (255, 30, 30))
Confirmed with Andrew that functionality is not broken

2021-11-11 03:48 UTC, mly32 commented on OpticalNavigation/core/attitude.py
>  def formA(q):
curious what the transformation is doing. wondering if it can be cleaned up as a matrix multiplication with q plus an addition.

2021-11-11 03:50 UTC, mly32 commented on OpticalNavigation/core/find_algos/find_with_threepoint.py
> +def center_circle(s):
its probably out there somewhere but brief comments on these math heavy functions would be nice. doesnt have to be in docstring format

2021-11-11 03:54 UTC, mly32 commented
lots of work done :) I didn't look into this too deeply because I still don't understand much of opnav.

the .env stuff looks good.

wondering if some of the opnav tests' paths are going to be updated with an env var `"D:", "OpNav", "db", "satellite-db.sqlite"` (I project searched around for `os.path`)

2021-11-11 05:32 UTC, sjz38 commented on OpticalNavigation/core/attitude.py
>  def formA(q):
Might be worth looking into. I'll add that as a TODO

2021-11-11 05:37 UTC, sjz38 commented on OpticalNavigation/core/find_algos/find_with_hough_transform_and_contours.py
> +        cam_DCM: np.ndarray = np.linalg.inv(camera_params.cam1Rotation)
Good point. I'll change it once I can confirm the results are the same

2021-11-11 05:38 UTC, sjz38 commented on OpticalNavigation/core/find_algos/find_with_threepoint.py
> +def center_circle(s):
@adamrnasir worked on this, if he wants to add any comments

2021-11-11 05:39 UTC, sjz38 commented on OpticalNavigation/core/find_algos/find_with_threepoint.py
> +def center_circle(s):
@adamrnasir worked on this, if he wants to add comments

2021-11-11 05:40 UTC, sjz38 commented
@mly32 what are these other paths?

2021-11-11 06:42 UTC, sjz38 commented
A little bit of a problem... somehow the results of our `test_pipeline` have become corrupted somewhere along the process of this PR. I've narrowed it down to somewhere between these two commits.https://github.com/Cislunar-Explorers/FlightSoftware/compare/7cd6605...29057bc
7cd6605 is the last working commit that has the correct outputs of `test_pipeline`, and 29057bc is the first commit after that which gives a wrong output. Pretty much the only thing that happens here is when we merge master into this branch. I'll work on this tomorrow as well, but any feedback would be appreciated

2021-11-11 07:35 UTC, tmf97 requested changes
Oh boy that was a lot to get through.

please make smaller PRs in the future

I was up very late reviewing this so apologies if i missed something or am sounding rude.
It's practically impossible to tell which files are actually useful/relevant/up-to-date by just looking at the code (sure there's commit history). all files that are no longer relevant should be clearly labelled/commented as such.

I've added my comments inline for clean up stuff.

We copy/paste code way too much - use imports!

I'd like to see individual modules of code with clear interfaces get defined soon. Every implementation of find I'm seeing seems to have different inputs and outputs. Something which may help with this is to define an abstract class for a find algo, and every concrete class is an implementation of a find algo. But please do this in a different PR. Something like this:
```python
class FindAlgo(ABC):
    @abstractmethod    
    def find(inputs: input_classes) -> output_classes:
        pass
```

and then for each algo you have:
```python
class FindWithContours(FindAlgo):
    def find(inputs: input_classes) -> output_classes:
        <insert implementation>
```

2021-11-11 07:35 UTC, tmf97 commented on OpticalNavigation/core/opnav.py
> +    frames = glob.glob("/home/stephen/Desktop/surrender_images/cislunar_case1c/*.jpg")
We need to figure out a better way to go about testing the full opnav pipeline than commenting in/out the right lines of code. Something like a flag: 
```
if TESTING_OPNAV:
    # load images from disk, with filename defined in .env file or a parameter somewhere
else:
    # take picture with Pi cameras
```

We need to clean this up

2021-11-11 07:35 UTC, tmf97 commented on OpticalNavigation/core/opnav.py
> +    '''
Same as above. We can't rely on commenting out code to do testing. We want to make this something that's clean and something you're proud to show to the world.

2021-11-11 07:35 UTC, tmf97 commented on OpticalNavigation/core/opnav.py
> +    )
I liked the original better :/
welp

2021-11-11 07:35 UTC, tmf97 commented on OpticalNavigation/core/opnav.py
> +        ONE_OR_LESS_GYROMEAS_ENTRY_FOUND: Gyro measurements db is less than one
So...is it less than one, or less than or equal to one? Choose one, not both

2021-11-11 07:35 UTC, tmf97 commented on OpticalNavigation/experiments/extract_frames_test_v2.py
> +from OpticalNavigation.core.preprocess import extract_frames
We shouldn't have two versions of this file; pick one, not both, unless there's a compelling reason to keep both.

2021-11-11 07:35 UTC, tmf97 commented on OpticalNavigation/experiments/extract_frames_test_v2.py
> +        select_camera(id=i)
I am vehemently against how `select_camera` and `record_video` both initialize new `Camera` and `CameraMux` hardware objects every time they're called - this takes up a good amount of time and memory. The Camera and CameraMux objects should be created once, and then their methods called as many times as needed.
I know this comment is in the wrong file (should be in `sense.py` but I just noticed it here)

2021-11-11 07:35 UTC, tmf97 commented on OpticalNavigation/tests/test_pipeline.py
> +    )
Please replace with `np.diag`

2021-11-11 14:38 UTC, sjz38 commented on OpticalNavigation/core/opnav.py
> +        ).reshape(3, 3)
Never crossed my mind to make a function, but makes sense. I can add one

2021-11-11 14:38 UTC, sjz38 commented on OpticalNavigation/core/opnav.py
> +        ).reshape(3, 3)
same as above

2021-11-11 14:38 UTC, sjz38 commented on OpticalNavigation/core/opnav.py
> +        coordArray = np.array(
see above

2021-11-11 14:40 UTC, sjz38 commented on OpticalNavigation/core/opnav.py
> +    '''
This doesn't can be run fine, its just I never got around to making sure it still works this semester. I think I just need to change something with the way the time is defined and it should be good to go. This can be run on both Pi and laptop

2021-11-11 15:17 UTC, sjz38 commented on OpticalNavigation/experiments/extract_frames_test_v2.py
> +from OpticalNavigation.core.preprocess import extract_frames
so v2 was a test that made sure the new frame extraction could create images from the video frames. the non-v2 also tests for correct transformation from camera timestamp to unix timestamp. Seems like v2 is a subset of the non-v2 test... I forget why

2021-11-11 15:22 UTC, sjz38 commented on OpticalNavigation/core/find_algos/find_with_hough_transform_and_contours.py
> +    r[:, :, 2, 2] = cth + u[2] ** 2 * (1 - cth)
This is some matrix math optimization that Muhlberger did

2021-11-11 15:25 UTC, sjz38 commented on OpticalNavigation/core/find_algos/find_with_hough_transform_and_contours.py
> +class Camera:
`Camera` in core/camera.py is the actual PiCamera object, while `Camera` here is a representation of the camera's characteristics that are relevant for coordinate transformations (fov, other coordinate). I can rename them, since it isn't the most clear

2021-11-11 15:27 UTC, sjz38 commented on OpticalNavigation/core/find_algos/find.py
> +MOON_HSV_BOUNDARIES = [([0, 0, 1], [179, 255, 254])]
`find.py` is deprecated. This was the initial implementation that use `HoughCircles` on the entire image. I'll add a readme to the find_algos folder to provide more information on each implementation and its status

2021-11-11 15:28 UTC, sjz38 commented on OpticalNavigation/core/const.py
>          c3az = math.radians(c3az)
This is camera 1 angle off the z axis. These angles define the physical orientation of the cameras on the satellite and are used to construct our rotation matrices

2021-11-11 15:30 UTC, sjz38 commented on OpticalNavigation/core/find_with_contours.py
>      return (xl, yl, xr - xl, yr - yl)
We have different self-sustaining find algorithms currently, but it probably would make sense to set up an interface now that we have a lot of shared functions from Muhlberger's script. As you mentioned, we'll do this in another PR

2021-11-11 18:13 UTC, sjz38 commented on OpticalNavigation/core/find_algos/find_with_hough_transform_and_contours.py
> +def __findBody(img, thresh, body, w, h):
@andxu282

2021-11-11 18:16 UTC, sjz38 commented on OpticalNavigation/core/find_with_contours.py
> +            # Rolling shutter correction
Because we don't have a main interface for find_algos. I.e. what would we import it from? Will update in another PR

2021-11-11 18:17 UTC, sjz38 commented on OpticalNavigation/core/opnav.py
> +    frames = glob.glob("/home/stephen/Desktop/surrender_images/cislunar_case1c/*.jpg")
I think it may be best to clean it up in another PR. Do you agree?

2021-11-11 20:40 UTC, tmf97 commented on OpticalNavigation/core/find_algos/find.py
> +MOON_HSV_BOUNDARIES = [([0, 0, 1], [179, 255, 254])]
Ok, we should delete/move/label (in my order of preference) old code like this.

2021-11-11 20:40 UTC, tmf97 commented on OpticalNavigation/core/find_algos/find.py
> +            for _ in range(0, 1):
deprecated code, no need to respond for this PR

2021-11-11 20:42 UTC, tmf97 commented on OpticalNavigation/core/opnav.py
> +    frames = glob.glob("/home/stephen/Desktop/surrender_images/cislunar_case1c/*.jpg")
Yup!

2021-11-11 20:50 UTC, tmf97 commented on OpticalNavigation/core/find_with_contours.py
>      return (xl, yl, xr - xl, yr - yl)
You don't need to define any interface, although that would be nice. 

In `find_with_hough_transform_and_contour.py` you can literally just
```python
from core.find_with_contours import reamp_roi
```
and use `remap_roi` wherever you need it

2021-11-11 20:52 UTC, sjz38 commented on OpticalNavigation/core/find_with_contours.py
>      return (xl, yl, xr - xl, yr - yl)
Yeah but I don't want any dependencies _between_ algorithms since it doesn't make sense. That's why either a utils file or an interface is better imo

2021-11-11 21:09 UTC, tmf97 commented on OpticalNavigation/core/find_with_contours.py
>      return (xl, yl, xr - xl, yr - yl)
Gotcha, yeah I'm a fan of some utils

2021-11-12 00:38 UTC, sjz38 commented on OpticalNavigation/core/const.py
>          c3az = math.radians(c3az)
Added a comment at the start of the function. I think that should be good

2021-11-12 01:27 UTC, adamrnasir commented on OpticalNavigation/core/find_algos/find_with_threepoint.py
> +def center_circle(s):
Just added a few explanatory comments.

2021-11-12 03:17 UTC, tmf97 commented on OpticalNavigation/experiments/extract_frames_test_v2.py
> +        select_camera(id=i)
This is for a different PR tho

2021-11-12 03:22 UTC, tmf97 commented on OpticalNavigation/core/find_algos/find_with_hough_transform_and_contours.py
> +    r[:, :, 2, 2] = cth + u[2] ** 2 * (1 - cth)
I guess it works!

2021-11-12 03:30 UTC, tmf97 reviewed
still got some things I want to get cleaned up, I can get a PR up tonight

2021-11-12 03:30 UTC, tmf97 commented on OpticalNavigation/tests/test_pipeline.py
> +    )
bump

2021-11-12 03:35 UTC, sjz38 commented
On it now

2021-11-12 04:18 UTC, sjz38 commented
Replaced all `np.array` with `np.diag`

2021-11-12 04:27 UTC, sjz38 commented on OpticalNavigation/core/opnav.py
> +        ONE_OR_LESS_GYROMEAS_ENTRY_FOUND: Gyro measurements db is less than one
Sean worked on this, and I haven't looked too much into this mechanism (though we'll probably need it for the opnav-FSW interface). I don't want to change anything without knowing what it does. I can add it as a TODO for the future

2021-11-12 04:32 UTC, tmf97 commented on OpticalNavigation/core/opnav.py
> +        ONE_OR_LESS_GYROMEAS_ENTRY_FOUND: Gyro measurements db is less than one
Copy. yeah todo

2021-11-12 04:33 UTC, tmf97 commented on OpticalNavigation/core/find_algos/find_with_hough_transform_and_contours.py
> +class Camera:
Bump on renaming this. Once this and the `Camera` class in find_with_contours get renamed I'd be good to accept

2021-11-12 04:33 UTC, sjz38 commented on OpticalNavigation/core/find_with_contours.py
> +        highThreshBlue = cv2.inRange(img, (5, 0, 0), (255, 255, 255))
I already have a TODO at the top of each of the measure functions

2021-11-12 04:34 UTC, sjz38 commented on OpticalNavigation/core/find_with_contours.py
>          u = np.linalg.inv(camera_params.cam3Rotation).dot(u)
Agreed - for a future PR

2021-11-12 04:40 UTC, sjz38 commented
Ok, I'll get on that. The only other thing is that for some reason the `test_pipeline` pytest only works if I call it from FlightSoftware root - its something to do with where the code is looking for the DB file. This workaround works for now, but I can investigate that later

2021-11-12 04:53 UTC, sjz38 commented on OpticalNavigation/core/find_algos/find_with_hough_transform_and_contours.py
> +class Camera:
Just changed `Camera` to `PiCam` (should be evident which one this is now). We good?

2021-11-12 05:13 UTC, sjz38 commented
@tmf97 Is there anything else I need to change?

2021-11-12 13:16 UTC, tmf97 approved these changes
~Nice~

There's always more stuff to change. This is a good stopping point for now

2021-11-12 21:46 UTC, merged