Center find feature testing
Cislunar-Explorers/FlightSoftware pull request #118
Opened 2021-11-18 19:30 UTC by andxu282

### Summary

This PR addresses Jira ticket [CISLUNAR-88](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-88)     
- Added feature testing for center finding algorithm
- Generates csv file with results file
- Generates two png files each containing a histogram, one for the center error and one for the radius error
- Feature testing from the terminal
- Add opnav sim code and data (output json and images) to repo, as well as CI support

### Testing

- Mostly just feature testing

### Notes

### Comments
- [x] Add an x between the brackets if you commented your code well!

2021-11-19 21:04 UTC, sjz38 commented on OpticalNavigation/core/find_algos/find_with_hough_transform_and_contours.py
> -    s[:, :, 0] = xx * zm
I believe that the sim and fsw differ in how the camera frame is defined (see Muhlberger's comment from 11/18). Are you sure that our coordinate frames are still being defined as intended?

2021-11-19 21:06 UTC, sjz38 commented on OpticalNavigation/core/find_algos/find_with_hough_transform_and_contours.py
> -    x = 2 * s[:, :, 0] / (1 - s[:, :, 2])
Same here with flipped signs vs. tiled_remap.py in sim code

2021-11-19 21:06 UTC, sjz38 commented on OpticalNavigation/core/find_algos/find_with_hough_transform_and_contours.py
> -class Camera:
@adamrnasir were there any other differences between the fsw Camera/projection code and the sim's tiled_remap.py beside the flipped signs I mentioned?

2021-11-19 21:09 UTC, sjz38 commented on OpticalNavigation/core/find_algos/find_with_hough_transform_and_contours.py
> +        u = np.linalg.inv(camera_params.cam1Rotation).dot(u)
You might have to revert these changes for formatter/pyright reasons

2021-11-19 21:11 UTC, sjz38 commented on OpticalNavigation/core/find_algos/find_with_hough_transform_and_contours.py
> -    s[:, :, 0] = xx * zm
If for testing purposes you are using Muhlberger's convention of the camera frame (tiled_remap.py) then you should make that very clear

2021-11-19 21:13 UTC, sjz38 commented on OpticalNavigation/core/find_algos/test_center_finding.py
> +    frames_dir = os.path.join(dir, "images/")
It is best to avoid directly using non-repo file paths in tests since it makes it more difficult for us to test these ourselves and integrate them into CI. We're thinking of ways we can best incorporate the sim data/images, to stay tuned for an update!

2021-11-19 21:15 UTC, sjz38 commented on OpticalNavigation/core/find_algos/test_center_finding.py
> +    frames_dir = os.path.join(dir, "images/")
But its still better that you added the directory as a CLI input as opposed to hard coding it like I was doing 😅

2021-11-19 21:18 UTC, sjz38 commented on OpticalNavigation/core/find_algos/tiled_remap.py
> +from dataclasses import dataclass
As we mentioned, this is a good idea refactoring all the transformation/projection functions into their own file which our find algos can use

2021-11-19 21:24 UTC, sjz38 commented on OpticalNavigation/core/find_algos/find_with_hough_transform_and_contours.py
> +def findStereographic(src, camera_params: CameraParameters = CisLunarCameraParameters):
What is the difference between `find` and `findStereographic`? may help to put a comment or two...

2021-11-19 21:29 UTC, sjz38 requested changes
Please make sure the CI passes. You can take a look at how the build is failing from the PR. Also make sure to resolve whatever conflicting files are still present

2021-11-30 20:16 UTC, sjz38 commented on OpticalNavigation/core/find_algos/test_center_finding.py
> +import json
Move this into the` OpticalNavigation/tests` folder

2021-11-30 20:28 UTC, sjz38 commented on OpticalNavigation/core/find_algos/test_center_finding.py
> +    are located (images, observations.json, and cameras.json files). It then uses the find algorithm to determine
How many images are part of the datasets we generated from the sim (in the repo)? Probably worth adding at least one of these image sets so we can have an end to end test run automatically

2021-11-30 20:37 UTC, sjz38 commented on OpticalNavigation/core/find_algos/test_center_finding.py
> +        _, body_vals = find(frame, st=True) if st_gn == "st" else find(frame)
Ah, I see. So your find function returns both 3D vectors in camera frame as well as pixel coordinates?

2021-11-30 20:42 UTC, sjz38 commented on OpticalNavigation/core/find_algos/test_center_finding.py
> +def test_center_finding(dir, results_file, st_gn):
It would be great if we could make this test extensible so that we can just swap find algorithms. I know your find algorithm interface is a bit different, so I'd say we can leave this as a near-future TODO, once we more formally agree on a find algorithm interface

2021-11-30 20:48 UTC, sjz38 commented on OpticalNavigation/core/find_algos/test_center_finding.py
> +    Generates the histogram of the difference between the truth value and the found value.
I would specify the value here is center or radius

2021-11-30 21:03 UTC, sjz38 commented on OpticalNavigation/core/find_algos/test_center_finding.py
> +    Run "python3 test_center_finding.py -d=<DIRECTORY> -r=<RESULTS_FILE>
I take it to fully run the test you first need to run `test_center_finding` and then run `__main__`.  I like the controllability you have with this setup, but I don't think this will work in our CLI. I'd suggest adding functionality that can run your test end to end (from image/sim data to histograms) which also evaluates the results based on a how off the find algorithm is from the truth values (I want there to be a test pass/fail condition)

2021-11-30 21:05 UTC, sjz38 requested changes
Two points:
- Once you add images to the repo, I want to run your test before approving
- I need you to make a few changes so that your test can be integrated into automated testing effectively
Great work!

2021-11-30 21:07 UTC, sjz38 commented
Also make sure to resolve the conflicting files!

2021-12-04 19:14 UTC, andxu282 commented on OpticalNavigation/core/find_algos/test_center_finding.py
> +    Generates the histogram of the difference between the truth value and the found value.
It's actually neither, that's what the center_histogram and radius_histogram functions are for, it's just so that i can factor out common code

2021-12-04 22:52 UTC, sjz38 commented
- I don't think you pushed the images you added on your computer
- The conflicting files shown at the bottom of this page need to be resolved or else we can't merge
- I'm looking into how we can get your unittest added to the CI

2021-12-07 03:47 UTC, sjz38 approved these changes
Approved!

2021-12-07 03:54 UTC, merged