Gom revisit
Cislunar-Explorers/FlightSoftware pull request #141
Opened 2022-01-11 08:15 UTC by tmf97

### Summary

This PR standardizes the gom interface using loadswitch objects. 

### Testing

Will need to flatsat test this - not sure how good mocking will be. 

### Notes

### Comments
- [x] Add an x between the brackets if you commented your code well!

2022-01-24 20:59 UTC, sjz38 commented on drivers/power/loadswitch.py
> +
Very cool idea! Just wondering, what motivated you to make this change?

2022-01-24 20:59 UTC, sjz38 commented on drivers/power/loadswitch.py
> +class mockGPIOLoadSwitch(GPIOLoadSwitch):
Add comment about using this one for simulation testing

2022-01-24 21:03 UTC, sjz38 commented on HITL-tests/gom_console.py
>  gom = Gomspace()
Don't we need an import here to gom.py?

2022-01-24 21:06 UTC, sjz38 commented on drivers/power/loadswitch.py
> +    def pulse(self):
Add parameter to specify length of pulse

2022-01-24 21:12 UTC, sjz38 commented on drivers/power/HITL_testing/burnwires-test.py
> +    gom_controller.burnwire.pulse(2)  # TODO, use gom's async instead of threading
You were using threading here because you wanted to read the gyro while running the burnwire, right?

2022-01-24 21:21 UTC, sjz38 commented on drivers/gom.py
> +        self.pa = ls.power_amplifier(self.driver)
I usually prefer to keep the variable names identical to what they are being set to so it is easier to track where that variable comes from. Nothing necessary, just my two cents

2022-01-24 21:22 UTC, sjz38 requested changes
Nice overhaul! I presume the way we would test this is by running all our old p31u tests that were updated and see if anything is wrong with them?

2022-01-24 21:51 UTC, tmf97 commented on drivers/power/HITL_testing/burnwires-test.py
> +    gom_controller.burnwire.pulse(2)  # TODO, use gom's async instead of threading
Yup, but they are both using the same I2C bus, and you can't have the Pi make I2C calls concurrently (the kernel makes it all "single threaded" anyways). This affects the speed at which we can poll the gyro (see the 1 second mark in https://cornell.app.box.com/file/758942694967 to see how the gom i2c calls delay the gyro calls). We can make this a non-issue using the gom's delay function

2022-01-24 21:51 UTC, tmf97 commented on drivers/gom.py
> +        self.pa = ls.power_amplifier(self.driver)
Makes sense

2022-01-24 21:52 UTC, tmf97 commented on drivers/power/loadswitch.py
> +class mockGPIOLoadSwitch(GPIOLoadSwitch):
yar

2022-01-24 21:54 UTC, tmf97 commented on drivers/power/loadswitch.py
> +
Have been thinking more about quality of life and system interfaces recently. The previous implementation was inconsistent and I always found myself wondering how to use the gom object (which is a bad sign since we wrote most of it)

2022-01-24 21:55 UTC, tmf97 commented on HITL-tests/gom_console.py
>  gom = Gomspace()
It's there, you just need to click on the blue dots on the left to see it in the PR

2022-01-24 22:28 UTC, tmf97 commented
That will suffice for the gom-related stuff. I will probably have to get a multimeter and verify the GPIO though

2022-01-24 22:49 UTC, sjz38 commented on drivers/power/loadswitch.py
> +    The `set` method will still work, but should not be used to properly actuate the solenoid valve.
What might be good here is to override the 'set' function here and have it do nothing (or print something). This will make sure that it doesn't accidentally do bad things. Also, it removes the functionality of 'set' in this class, which helps since the solenoid should only be truggered through a pulse.

2022-01-24 22:50 UTC, sjz38 requested changes
Looks good. See comment about solenoid

2022-01-25 00:07 UTC, tmf97 commented on drivers/power/loadswitch.py
> +    The `set` method will still work, but should not be used to properly actuate the solenoid valve.
Good idea!

2022-02-22 02:34 UTC, sjz38 commented on HITL-tests/gom_console.py
> -                gom.solenoid.set(True)
Shouldn't we really be calling `pulse` here? My thought is that we shouldn't be running `set` or _`set` at all for the solenoid

2022-02-22 02:37 UTC, sjz38 reviewed
Idk if you also want to merge master in but once you address my comment I'll approve

2022-02-22 03:01 UTC, tmf97 commented on HITL-tests/gom_console.py
> -                gom.solenoid.set(True)
I want there to be an option to turn on/off the pin on the P31u that is allocated to the solenoid valve, but not have the restrictions of the `pulse` command. Think about if you're debugging the harnessing and just want to set the pin high without any valve connected - it'd be VERY difficult to see a response on a multimeter if the pin is only high for 400ms. The changes I've made try and enforce that

2022-02-22 03:01 UTC, tmf97 commented
> Idk if you also want to merge master in but once you address my comment I'll approve

Why would I write code if I didn't want to merge into master?????

2022-02-22 03:12 UTC, sjz38 commented
Merge master into this branch

2022-02-22 03:13 UTC, sjz38 approved these changes
👍

2022-02-22 03:15 UTC, tmf97 commented
Oh sorry I completely misunderstood what you said. Github says `This branch has no conflicts with the base branch` so no need to merge master into this branch

2022-02-22 03:15 UTC, merged

2022-02-22 04:12 UTC, tmf97 commented
Lesson learned: just because there's no merge conflict doesn't mean there will be no errors caused by the merge