Cleanup and Enumification
Cislunar-Explorers/FlightSoftware pull request #142
Opened 2022-01-16 08:43 UTC by tmf97

### Summary

This PR groups the kwarg string definitions in constants.py into enums, and propagates those changes to all of FSW.
Also, some minor improvements to commands and the command handler

### Testing

No "new" code, old unit tests should suffice (famous last words)

### Notes

Is it de-jank or un-jank?

### Comments
- [x] Add an x between the brackets if you commented your code well!

2022-01-24 21:38 UTC, sjz38 commented on utils/constants.py
> +class CommandKwargs(StringEnum):
Comments to the new Enums you made wouldn't hurt

2022-01-24 21:43 UTC, sjz38 commented on communications/codecs.py
>  # beware integer underflow erro
erro -> error

2022-01-24 21:44 UTC, sjz38 commented on communications/command_definitions.py
> +    GomConfKwargs,
Seems like you could name this gk, if we're being consistent with the other Kwarg imports

2022-01-24 21:50 UTC, sjz38 commented on communications/command_definitions.py
remove empty line

2022-01-24 22:00 UTC, sjz38 requested changes
👍I'll approve after you address my comments

2022-01-24 22:53 UTC, tmf97 commented on communications/command_definitions.py
> +    GomConfKwargs,
Yeah, but not that important

2022-01-24 22:55 UTC, tmf97 commented on communications/command_definitions.py
Can't :)
https://www.python.org/dev/peps/pep-0008/#blank-lines

2022-02-22 02:15 UTC, sjz38 commented on utils/constants.py
> +class CommandKwargs(StringEnum):
Reminder ^

2022-02-22 02:25 UTC, sjz38 approved these changes
👍

2022-02-22 02:27 UTC, merged