Transform verification
Cislunar-Explorers/FlightSoftware pull request #146
Opened 2022-02-12 20:50 UTC by adamrnasir

### Summary

This PR addresses Jira ticket [CISLUNAR-89](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-89) 

Wrote test_reprojections.py to determine accuracy of reprojection between gnomonic and stereographic images (asserts that computed difference is less than 0.15). Additionally added image test set (identical to traj-case1c images but without orange line surrounding stereographic contours).

### Testing
Code is a test case, all cases pass.

### Notes
In the future, need to move image test set to an appropriate location (within simulations folder).

### Comments
- [x] Add an x between the brackets if you commented your code well!

2022-02-14 04:50 UTC, sjz38 commented
I know you've reached out to Andrew (and mentioned it in the PR), but make sure that the images are all stored in the simukations forlder for this PR.

2022-02-14 04:53 UTC, sjz38 commented on OpticalNavigation/tests/test_reprojections.py
> +                        self.write_composite_image(outc, tgtc, cmp, gnName, i, j)
This function call is missing an argument for the `diff ` parameter. This makes it not able to output images

2022-02-14 04:56 UTC, sjz38 commented on OpticalNavigation/tests/tiled_remap.py
> +from dataclasses import dataclass
Let's use the tiled_remap file in `core/find_algos/`. We don't want multiple instances of the same file

2022-02-14 04:57 UTC, sjz38 commented on OpticalNavigation/tests/tiled_remap.py
> +from dataclasses import dataclass
Let's use the tiled_remap file in `core/find_algos/`. We don't want multiple instances of the same file

2022-02-14 04:59 UTC, sjz38 requested changes
Looks good! I want to see the generated images on my end, so once you get to fixing that bug, I can approve!

2022-02-14 05:16 UTC, sjz38 commented on OpticalNavigation/tests/test_reprojections.py
> +        gnomonicList = glob.glob("images/*_gn.png")
Might want to wrap the `glob.glob` in a `sorted()` so it is not completely random. It will go f0, f10, f11, ... f1, f2, but prob better than nothing

2022-02-14 23:24 UTC, sjz38 commented
Also add your test to `setup.cfg` so it automatically runs on CI

2022-02-19 00:18 UTC, tmf97 requested changes

2022-02-19 00:18 UTC, tmf97 commented on OpticalNavigation/tests/test_reprojections.py
> +import tiled_remap
```suggestion
from OpticalNavigation.find_algos import tiled_remap
```

2022-02-19 18:40 UTC, andxu282 approved these changes

2022-02-19 20:37 UTC, adamrnasir commented on OpticalNavigation/.gitignore
> -tests/*.png
Long story short, yes — this was the subject of some debate last semester, but ultimately there was not a good way around the fact that Andrew's test and mine both require an image set to test upon. Andrew's images are currently located in OpticalNavigation/simulations/sim/data, which is where I will be moving mine. The difference between the sets is that bodies in the existing images have an outline around them, whereas those I'm adding were generated without such an outline.

2022-02-19 20:37 UTC, adamrnasir commented on OpticalNavigation/tests/test_reprojections.py
> +        gnomonicList = glob.glob("images/*_gn.png")
Done!

2022-02-19 20:37 UTC, adamrnasir commented on OpticalNavigation/tests/tiled_remap.py
> +from dataclasses import dataclass
Done!

2022-02-19 20:40 UTC, adamrnasir commented on OpticalNavigation/tests/tiled_remap.py
> +from dataclasses import dataclass
Understood. This was a consequence of Andrew and I both adding tiled_remap.py (authored by Dr. Muhlberger) to the repo separately — and in separate locations, no less — to use for our individual tests. We should have decided on a location beforehand, then both referenced it there. Sorry!

2022-02-19 20:49 UTC, adamrnasir commented on OpticalNavigation/.gitignore
> -tests/*.png
Nonetheless, I will add "tests/*.png" back to this file, since I'm moving those images anyway. Agreed there shouldn't be images in test directory or subdirectories thereof.

2022-02-21 14:34 UTC, tmf97 requested changes
There are some code organizational issues in here that need addressing (and probably for all of the opnav code - I need to investigate further). This is something that I think has been endemic to the team for a while now though so I don't blame you if you've just been pattern-matching.

2022-02-21 14:34 UTC, tmf97 commented on OpticalNavigation/tests/test_reprojections.py
> +    def get_ucam(self, name):
This function seems like it's critical for some other areas of FSW. Having it defined in a test class like this makes it essentially impossible to access/import into another file. Please cut+paste this function to another file (either already existing or a new file) and import it everywhere it's needed.

2022-02-21 14:34 UTC, tmf97 commented on OpticalNavigation/tests/test_reprojections.py
> +        """Returns u_cam from filename."""
What is `u_cam`? Is is the normalized vector that a camera is pointing in, in the spacecraft's body reference frame?

2022-02-21 14:34 UTC, tmf97 commented on OpticalNavigation/tests/test_reprojections.py
> +                [5.00000000e-01, 6.12323400e-17, 8.66025404e-01], dtype=np.float32
All of these arrays should be defined in constants.py or somewhere else - not in a testing class. 
In constants.py it should be something like:
```
CAM_A_UX = 5.0e-1
CAM_A_UY = ...

CAM_B_UX = ...
CAM_A_U = np.array([CAM_A_UX,...

CAM_VECTORS = {"camA": CAM_A_U, "camB": CAM_B_U, ... }
```

Then in this file you:
`from utils.constants import CAM_VECTORS`

We want to do this so that this code/parameters are easily accessible and reusable by different parts of FSW. Defining the code you're testing in the test class itself is a bit circular and is not future-proof.

2022-02-21 14:34 UTC, tmf97 commented on OpticalNavigation/tests/test_reprojections.py
> +                [-5.00000000e-01, -6.12323400e-17, -8.66025404e-01], dtype=np.float32
The machine precision of a float32 is only ~6e-8, and float64 only ~1e-16. Is -6.123e-17 supposed to be just 0 instead?

2022-02-21 14:34 UTC, tmf97 commented on OpticalNavigation/tests/test_reprojections.py
> +    def get_ucam(self, name):
A hint for figuring out whether to define a function in a class or have it be defined on its own is whether or not you're using the `self` parameter in the function definition. If there is no use of `self` in the function you're writing in a class, chances are you want to define that function elsewhere and import it.

2022-02-23 19:54 UTC, adamrnasir commented on OpticalNavigation/tests/test_reprojections.py
> +        """Returns u_cam from filename."""
That's correct.

2022-02-23 19:54 UTC, adamrnasir commented on OpticalNavigation/tests/test_reprojections.py
> +                [5.00000000e-01, 6.12323400e-17, 8.66025404e-01], dtype=np.float32
Per Dr. Muhlberger, "The "camera frame" in the sim/tiled_remap and in current FSW are upside-down wrt one another... This disagreement, while likely to cause confusion, isn't anything fundamental" — these u_cam values are specific to the sim (and thus this test) and are therefore not consistent with FSW as a whole.

2022-02-23 19:57 UTC, adamrnasir commented on OpticalNavigation/tests/test_reprojections.py
> +    def get_ucam(self, name):
I'm not entirely sure about this— this function is only designed to parse filenames produced by Dr. Muhlberger's opnav sim. Additionally, the u_cam values quoted within are not consistent with FSW (see https://github.com/Cislunar-Explorers/FlightSoftware/pull/146#discussion_r813264198)

2022-02-23 20:12 UTC, adamrnasir commented on OpticalNavigation/tests/test_reprojections.py
> +                [-5.00000000e-01, -6.12323400e-17, -8.66025404e-01], dtype=np.float32
I believe you're correct.

2022-02-23 21:57 UTC, tmf97 commented on OpticalNavigation/tests/test_reprojections.py
> +        """Returns u_cam from filename."""
Please add comments so people don't have to guess

2022-02-23 21:58 UTC, tmf97 commented on OpticalNavigation/tests/test_reprojections.py
> +                [5.00000000e-01, 6.12323400e-17, 8.66025404e-01], dtype=np.float32
Ok. Let's get everything consistent in another PR

2022-02-23 22:04 UTC, tmf97 approved these changes

2022-02-23 23:48 UTC, sjz38 approved these changes
👍 Time for the good ol' squash 'n merge

2022-02-23 23:50 UTC, merged