Opnav cleanup
Cislunar-Explorers/FlightSoftware pull request #147
Opened 2022-02-17 03:27 UTC by sjz38

### Summary

This PR addresses Jira tickets [CISLUNAR-105](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-105), [CISLUNAR-106](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-106), [CISLUNAR-107](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-107), [CISLUNAR-109](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-109), [CISLUNAR-110](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-110), [CISLUNAR-111](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-111)     
This PR makes many quality of life changes to the opnav module, most important of which is the refactoring of the observe functions defined in `opnav.py` into their own module, as well as making the data flow more understandable. Ephemeris code was also resurrected and changed to use unix timestamps instead of datetimes.

### Testing

Code was tested using the `test_pipeline.py` script and was ensured that the results were the same. Additionally, ephemerides using unix timestamps were compared against the datetime results for similarity (there was some difference presumably due to the change in timestamp units).

### Notes

@adamrnasir , @andxu282 : Make sure you understand the data flow in `opnav.py` and `observe_functions.py` 

### Comments
- [x] Add an x between the brackets if you commented your code well!

2022-02-17 04:42 UTC, tmf97 requested changes
Some small edits and comments

2022-02-17 04:42 UTC, tmf97 commented on OpticalNavigation/core/const.py
> +
`dataclass`es are your friend for this kind of stuff, but no need to change.

2022-02-17 04:42 UTC, tmf97 commented on OpticalNavigation/core/observe_functions.py
> +from core.find_algos.find_with_contours import *
Please no star imports

2022-02-17 04:42 UTC, tmf97 commented on OpticalNavigation/tests/test_pipeline.py
>  import numpy as np
Can we re-add this file back to the CI without much more effort?

2022-02-17 19:47 UTC, andxu282 commented on OpticalNavigation/core/opnav.py
> -def __get_elapsed_time(bestTuple, timeDeltaAvgs, observeStart):
So you basically moved all of these observe functions into observe_functions.py instead of keeping them here?

2022-02-17 19:52 UTC, andxu282 reviewed
I think overall, the changes look good, just a few clarifying questions
1. The biggest change was just then moving a bunch of the functions from opnav.py into observe_functions.py to make things more modular?
2. What does the ephemeris code do exactly?

2022-02-17 22:47 UTC, tmf97 commented
> 2. What does the ephemeris code do exactly?

We need to know where the Earth/Moon/Sun are in space at the time of an opnav run in order for us to "triangulate" where we are with respect to those bodies. The ephemeris codes calls astropy to calculate the location of these bodies at a point in time. Knowing the angular separation between the bodies is not enough information to determine where our spacecraft are - we also need to know the positions of these bodies in order to "invert" the system and figure out where we are in it. I'm honestly not sure where this "inversion" occurs (is it part of the Kalman filer?).

It's situations like this where solid, high-level documentation is really valuable!

2022-02-17 23:07 UTC, sjz38 commented
> > 2. What does the ephemeris code do exactly?
> 
> We need to know where the Earth/Moon/Sun are in space at the time of an opnav run in order for us to "triangulate" where we are with respect to those bodies. The ephemeris codes calls astropy to calculate the location of these bodies at a point in time. Knowing the angular separation between the bodies is not enough information to determine where our spacecraft are - we also need to know the positions of these bodies in order to "invert" the system and figure out where we are in it. I'm honestly not sure where this "inversion" occurs (is it part of the Kalman filer?).
> 
> It's situations like this where solid, high-level documentation is really valuable!

It's worth noting that we only get the ephemerides for the Moon and Sun because our measurements are taken in the ECI (Earth Centered Intertial) frame

2022-02-22 02:04 UTC, sjz38 commented on OpticalNavigation/tests/test_pipeline.py
>  import numpy as np
Currently, opnav.py is set up to use surrender images, so consequently, test_pipeline can't be added to the CI. Once we have are able to add the opnav sim, we can add test_pipeline to the CI. That would be something very good to have.

2022-02-22 02:04 UTC, sjz38 commented on OpticalNavigation/core/opnav.py
> -def __get_elapsed_time(bestTuple, timeDeltaAvgs, observeStart):
Yep, I also changed the function i/o to make them a little more maangeable

2022-02-22 02:05 UTC, sjz38 commented on OpticalNavigation/core/const.py
> +
Yeah, these were made by Sean a while back. I don't want to touch them until we test the code that uses them (the UKFs)

2022-02-22 02:09 UTC, sjz38 commented on OpticalNavigation/core/observe_functions.py
> +from core.find_algos.find_with_contours import *
Done

2022-02-22 02:32 UTC, tmf97 commented on OpticalNavigation/core/const.py
> +
Ok. This is beyond the scope of this PR but all the code depending on this will (probably) need to get completely overhauled anyways; we shouldn't allow legacy, poorly formatted/designed code to bog down the quality of our development (even if the code works - or we think it works).

2022-02-22 02:44 UTC, tmf97 commented on pyrightconfig.json
> +    "OpticalNavigation/core/opnav.py",
Can we remove any of these?

2022-02-22 02:44 UTC, tmf97 commented on OpticalNavigation/core/observe_functions.py
> +def record_with_timedelta(camNum, camera_rec_params):
Can you please add some type hinting on all of these functions? Type hinting at a function level (i.e. what it's inputs and outputs actually are) is a really effective way (for me at least) to understand what's going on

2022-02-22 02:44 UTC, tmf97 commented on OpticalNavigation/tests/test_pipeline.py
>  import numpy as np
Ok. I know there is a way to "install" another repo inside another repo (I've seen PAN do this) - I'll look into it.

2022-02-22 02:45 UTC, tmf97 commented on pyrightconfig.json
> +    "OpticalNavigation/core/opnav.py",
The `"OpticalNavigation/tests"` entry make pyright ignore all py files in the folder. Are there some we're able to type check?

2022-02-22 03:15 UTC, sjz38 commented on OpticalNavigation/tests/test_pipeline.py
>  import numpy as np
Do you mean having the surrender images in the private repo?

2022-02-22 03:17 UTC, sjz38 commented on pyrightconfig.json
> +    "OpticalNavigation/core/opnav.py",
We do have a few tests in `OpticalNavigation/tests` that can be un-ignored. I don't want to remove ukf.py and opnav.py yet because they have untested code

2022-02-22 03:21 UTC, tmf97 commented on OpticalNavigation/tests/test_pipeline.py
>  import numpy as np
Ah, no, nevermind what I said earlier.
Aren't we already able to add the opnav sim to our unit tests? (from OpticalNavigation/simulations/sim/)

2022-02-22 03:32 UTC, sjz38 commented on OpticalNavigation/tests/test_pipeline.py
>  import numpy as np
They are added through the form of Andrew's center_finding test and Adam's transform verification test

2022-02-24 02:29 UTC, sjz38 commented on OpticalNavigation/core/observe_functions.py
> +def record_with_timedelta(camNum, camera_rec_params):
Done

2022-02-24 02:47 UTC, tmf97 approved these changes
Please see comment

2022-02-24 02:47 UTC, tmf97 commented on OpticalNavigation/core/observe_functions.py
> +def get_detections(frames: "list[str]") -> "list[DetectionData]":
Didn't realize typing stuff as `"list[...]"` was valid syntax. Everything else I've ever seen (and can find) uses `List[...]`. Consider changing for consistency's sake.

2022-02-24 03:11 UTC, merged