Test runs now generate a separate directory
Cislunar-Explorers/FlightSoftware pull request #148
Opened 2022-02-17 20:39 UTC by andxu282

### Summary

This PR addresses Jira ticket [CISLUNAR-XX](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-140)     
- center find feature test now generates a separate directory based on the current unix time
- all results file are placed in this directory

### Testing

### Notes

### Comments
- [x] Add an x between the brackets if you commented your code well!

2022-02-17 22:30 UTC, tmf97 reviewed
Looks solid to me and runs on my machine. Gotta love being organized

2022-02-17 22:30 UTC, tmf97 commented on OpticalNavigation/tests/test_center_finding.py
> +        os.makedirs(
Nit: when I run `pytest` from the root directory, the results end up in `FlightSoftware/tests/`, is this the intended behavior?

2022-02-17 22:30 UTC, tmf97 commented on OpticalNavigation/tests/test_center_finding.py
> +            newline="",
I'd recommend using f-strings for stuff like this: https://realpython.com/python-f-strings/#f-strings-a-new-and-improved-way-to-format-strings-in-python

2022-02-22 01:51 UTC, sjz38 commented on OpticalNavigation/tests/test_center_finding.py
> +        os.makedirs(
I would recommend putting it in `OpticalNavigation/tests`

2022-02-22 02:11 UTC, sjz38 requested changes
Once you change the small things we mentioned, I'll be good to approve!

2022-02-24 17:25 UTC, tmf97 approved these changes

2022-03-01 22:41 UTC, sjz38 approved these changes
👍I'll merge since Andrew left

2022-03-01 22:41 UTC, merged