Body meas testing
Cislunar-Explorers/FlightSoftware pull request #160
Opened 2022-03-02 05:26 UTC by sjz38

### Summary

This PR addresses Jira ticket [CISLUNAR-90](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-90)     
Creates a unit test for the transformations involved from taking a stereographic image coordinate to a 3D vector in the satellite body frame at the start of acquisition. Uses generated sim trajectories found in `OpticalNavigation/simulations/sim/data`. Asserts a vector accuracy of >95%. Run `python test_body_meas.py` to see the vectors printed.

### Testing

This is a unit test PR. The test passes.

### Notes

Will have to look into how to incorporate angular size, but let's first get this part merged

### Comments
- [x] Add an x between the brackets if you commented your code well!

2022-03-02 16:01 UTC, sjz38 commented on OpticalNavigation/tests/test_body_meas.py
> +        return 4 * x / norm, 4 * y / norm, -(norm - 8) / norm
Ah, I knew I was forgetting something. There have to be two versions of this function because the spherical camera frames are defined differently between the sim and our code. But it shouldn't be defined in this test, yes. I should just be able to replace the implementation in tiled_remap.py with this one since this is what flight code should be using.

2022-03-02 17:12 UTC, tmf97 requested changes
Solid step in the right direction. Can you also please add all the currently valid opnav tests into the "include" section in the pyrightconfig.json. See sample in https://github.com/microsoft/pyright/blob/main/docs/configuration.md

2022-03-02 17:12 UTC, tmf97 commented on OpticalNavigation/tests/test_body_meas.py
> +        data = open(path)
Use a context manager instead of manually opening/closing a file. See the first minute of https://www.youtube.com/watch?v=qUeud6DvOWI

2022-03-02 17:12 UTC, tmf97 commented on OpticalNavigation/tests/test_body_meas.py
> +            # convention of opnav sim (timestamps have a decimal point)
We should change the opnav sim or FSW so the two produce consistent filenames

2022-03-02 17:12 UTC, tmf97 commented on OpticalNavigation/tests/test_body_meas.py
> +            logging.debug(f"Cam Vec: {camVec}")
Use `enumerate(zip(...))` here. See minute 4 of https://www.youtube.com/watch?v=qUeud6DvOWI

2022-03-02 19:04 UTC, sjz38 commented on OpticalNavigation/tests/test_body_meas.py
> +            # convention of opnav sim (timestamps have a decimal point)
Well the sim's timestamps are in the form of a dt, the time difference (in seconds) from the start of acquisition, however the FSW side uses absolute timestamps in microseconds. The sim filenames also use decimal points. I think it would be a bit extra to go about that considering that the filenames aren't used after this point

2022-03-02 19:07 UTC, sjz38 commented on OpticalNavigation/tests/test_body_meas.py
> +            logging.debug(f"Cam Vec: {camVec}")
I think something like `for f in fileInfo:` would be better to use here. Easier to understand and I don't need to zip multiple lists

2022-03-02 19:07 UTC, sjz38 commented on OpticalNavigation/tests/test_body_meas.py
> +        data = open(path)
Done

2022-03-02 19:56 UTC, tmf97 commented on OpticalNavigation/tests/test_body_meas.py
> +            logging.debug(f"Cam Vec: {camVec}")
Yeah! I like that better

2022-03-02 20:01 UTC, tmf97 requested changes
Solid stuff. I'd like to see something describing the test (what it's testing, how it's testing what it's supposed to test) for sake of everyone's understanding.

2022-03-03 03:35 UTC, sjz38 commented on OpticalNavigation/tests/test_body_meas.py
> +            data = open(path)
oops

2022-03-03 04:22 UTC, tmf97 commented on OpticalNavigation/tests/test_body_meas.py
> +            logging.debug(f"Cam Vec: {camVec}")
Do you still want to implement this?

2022-03-03 04:22 UTC, tmf97 approved these changes
If you want to rewrite the for loop, go for it

2022-03-03 04:24 UTC, tmf97 commented on OpticalNavigation/tests/test_body_meas.py
> +            # convention of opnav sim (timestamps have a decimal point)
Hmm ok. Ideally, the sim is something we would use to mock out the camera observations, and thus would have the same interface as the cameras. This is for a new PR, but we need to be consistent

2022-03-03 04:55 UTC, sjz38 commented on OpticalNavigation/tests/test_body_meas.py
> +            logging.debug(f"Cam Vec: {camVec}")
Yeah, you were actually right. I was iterating over multiple lists. Used the `enumerate(zip(...)))` syntax

2022-03-03 15:31 UTC, tmf97 approved these changes
Looks good!

2022-03-03 15:31 UTC, tmf97 commented on OpticalNavigation/tests/test_body_meas.py
> +        for i, (fileInf, stCenter, deltaT, truth) in enumerate(
I can't find where you use this `i`, if you don't need it, no need to use `enumerate`, `zip`ing is all you'll need

2022-03-03 15:41 UTC, sjz38 commented on OpticalNavigation/tests/test_body_meas.py
> +        for i, (fileInf, stCenter, deltaT, truth) in enumerate(
True, I'll fix it and merge

2022-03-03 15:47 UTC, merged