New command implementation
Cislunar-Explorers/FlightSoftware pull request #162
Opened 2022-03-07 22:25 UTC by RohitValiveti

### Summary

This PR:
- Addresses Jira ticket [CISLUNAR-154](https://cislunarsoftware.atlassian.net/browse/CISLUNAR-154)     
- Implements a new command to change the Earth/Sun/Moon threshold to help with testing the find_with_hough_transform_and_contours.findBody() opnav find algorithm

### Testing

- Tested with a unit test
- Find test in tests/command_test.py test_setEMSThresh()
- Tested uplinked data and downlinked

### Notes

- Looking through other command, one concern/thought I had was if this command may be redundant, given the existence of the set_param() command, which can change any single command. However, incorporating a single command for for changing every and only parameter of one particular find algorithm may be of use for testing

### Comments
- [x] Add an x between the brackets if you commented your code well!

2022-03-07 22:33 UTC, tmf97 approved these changes
Looks solid!
I see why this may feel a bit redundant, because the `set_param` command already exists. One functionality you could add to this command would to add some checks to the inputs before setting the parameter (i.e. is each parameter between 0 and 1? [or is it 0 to 255?]). This adds a safety net which prevents errors that could be cause by operator error or bit flips from radiation

2022-03-08 04:07 UTC, sjz38 commented on tests/command_test.py
> +    def test_setEMSThresh(self):
Add a comment here describing what the test is doing. See the other tests in this file for reference

2022-03-12 23:47 UTC, sjz38 commented
@tmf97 Did you want @RohitValiveti to implement the changes you suggested? I'm fine going ahead with the merge.

2022-03-12 23:49 UTC, RohitValiveti commented
My bad, I forgot to add the check. I'll get on that tonight

2022-03-13 01:31 UTC, RohitValiveti commented
@tmf97 @sjz38 Just added assert statements for the new threshold values to be between 0 and 1, lmk if you think its good

2022-03-13 01:41 UTC, sjz38 commented on utils/constants.py
> +    EARTH_THRESH = "earth threshold"
change these to be snake-case (add underscore instead of space)

2022-03-13 01:43 UTC, sjz38 requested changes
see above

2022-03-13 01:49 UTC, RohitValiveti commented
Just changed

2022-03-13 01:56 UTC, tmf97 approved these changes
Looks solid, feel free to Squash and Merge whenever. In the future let's lower the turnaround time on features like this

2022-03-13 02:00 UTC, merged