Add more comments to help implement commands
Cislunar-Explorers/FlightSoftware pull request #163
Opened 2022-03-07 22:28 UTC by tmf97

### Summary

This PR adds more in-line documentation to help implement more commands in the future

### Testing

N/A, just comments

### Notes

### Comments
- [x] Add an x between the brackets if you commented your code well!

2022-03-07 22:37 UTC, RohitValiveti approved these changes
Looks good! Feels nice to be able to understand your comments now 😂.. If you think it would be of use, we could also add documentation for how to write a command test. Your explanations definitely helped me, so just an idea.

2022-03-07 23:21 UTC, tmf97 commented
Good idea! Will get on how to write a command test

2022-03-08 04:16 UTC, sjz38 commented on utils/constants.py
> +GOM_TIMING_FUDGE_FACTOR = 3  # milliseconds
Would help to specify why this is a fudge factor/why we need it

2022-03-08 04:17 UTC, sjz38 commented on communications/commands.py
>      All you need to do if you want to implement a new command is to:
Directions a well written, easy to follow in conjunction with the commands already written

2022-03-08 04:18 UTC, sjz38 commented on communications/commands.py
> +        3b. Make syre that every value you define in the downlink_codecs list get returned in a dict by the `_method`.
Typo "syre" -> "sure"

2022-03-08 04:18 UTC, sjz38 requested changes
👍I'm good to approve, just a few nitpicks

2022-03-08 04:19 UTC, sjz38 commented
And resolve the conflicting file

2022-03-08 17:53 UTC, tmf97 commented on utils/constants.py
> +GOM_TIMING_FUDGE_FACTOR = 3  # milliseconds
Honestly I've forgotten why I put it there. Too scared to delete now 😬

2022-03-08 22:42 UTC, sjz38 commented on utils/constants.py
> +GOM_TIMING_FUDGE_FACTOR = 3  # milliseconds
Its in attitude_adjustment.py, line 106. Looks like you get rid of it in your timing branch

2022-03-08 22:43 UTC, sjz38 approved these changes
👍

2022-03-13 02:01 UTC, merged