MainSatelliteThread unittest
Cislunar-Explorers/FlightSoftware pull request #95
Opened 2021-08-16 03:24 UTC by tmf97

Adds a unit test for making sure that the `MainSatelliteThread` defined in main.py initializes without errors. I believe this test would have prevented #91 from slipping by.

2021-08-29 22:38 UTC, sjz38 requested changes
Please address the changes I mentioned in my comments

2021-08-29 22:38 UTC, sjz38 commented on communications/satellite_radio.py
> +    from adafruit_bus_device.spi_device import SPIDevice
Why are the edits from #94 copied over here? I feel that we shouldn't need to copy edits that are pending in another PR.

2021-08-29 22:38 UTC, sjz38 commented on tests/main_test.py
> +import unittest
I think it would be useful (and as policy going forward) to have a brief comment describing the purpose of a test. For instance, I can tell that this test is ensuring that certain variables are None/not None after initialization of MainSatelliteThread, however, I don't really know why this is needed, or what the motivation for making this test is. I think as we emphasize testing of our code more, knowing what each test case does through comments will help tremendously!

2021-08-29 22:38 UTC, sjz38 commented on tests/main_test.py
> +class MyTestCase(unittest.TestCase):
MyTestCase is not the most descriptive name for a test class...

2021-08-30 01:23 UTC, tmf97 commented on communications/satellite_radio.py
> +    from adafruit_bus_device.spi_device import SPIDevice
Because this PR depends on changes from 94, not sure how to git around this one

2021-08-30 01:23 UTC, tmf97 commented on tests/main_test.py
> +import unittest
Fantastic idea!

2021-08-30 01:24 UTC, tmf97 commented on tests/main_test.py
> +class MyTestCase(unittest.TestCase):
Ah whoopsies, forgot to change the pycharm default 😅

2021-08-30 02:50 UTC, sjz38 commented on communications/satellite_radio.py
> +    from adafruit_bus_device.spi_device import SPIDevice
Was the main-test branch created off of the voltage-switch branch? If so, that may be why

2021-08-30 03:28 UTC, tmf97 commented on communications/satellite_radio.py
> +    from adafruit_bus_device.spi_device import SPIDevice
yup!

2021-09-03 00:09 UTC, sjz38 commented on tests/main_test.py
> +"""
Perfect!

2021-09-03 00:09 UTC, sjz38 approved these changes
Perfect!

2021-09-03 00:13 UTC, tmf97 commented
ty!

2021-09-03 00:13 UTC, merged