Low battery
Cislunar-Explorers/FlightSoftware pull request #99
Opened 2021-09-07 03:09 UTC by tmf97

Closes #49 
Gives a rough draft of our low battery flight mode

2021-09-10 22:26 UTC, sjz38 requested changes

2021-09-10 22:26 UTC, sjz38 commented on telemetry/telemetry.py
> +        pass
Is this a #TODO?

2021-09-10 22:29 UTC, sjz38 commented on flight_modes/flight_mode.py
> +            self._parent.downlink_queue.put(downlink)
Is it that we can still run certain tasks in low battery mode? I guess we do (like maneuver, etc), but are we in the hopes that the battery won't drain to 0 for these tasks?

2021-09-15 02:49 UTC, tmf97 commented on flight_modes/flight_mode.py
> +            self._parent.downlink_queue.put(downlink)
We want to still be able to do tasks in low batt mode, just at a lower frequency to preserve power.

2021-09-15 02:50 UTC, tmf97 commented on flight_modes/flight_mode.py
> +    """FMID 3: Low Battery Safety Mode: the main goal here is to save power as much as possible in case we are in a
On it!

2021-09-15 02:50 UTC, tmf97 commented on telemetry/telemetry.py
> +        pass
yup

2021-09-15 02:50 UTC, tmf97 commented on flight_modes/flight_mode.py
> +                self._parent.gom.rf_transmitting_switch(
Ah yeah good point

2021-10-14 18:38 UTC, sjz38 commented on flight_modes/flight_mode.py
> +            self._parent.downlink_queue.put(downlink)
Should we update `self._parent.last_telem_downlink` here as well? Just looking at what is done in low battery mode

2021-10-14 18:42 UTC, sjz38 commented on telemetry/telemetry.py
> +    def query_telem(self):
Add # TODO

2021-10-14 18:44 UTC, sjz38 requested changes
See comments for the questions I have

2021-10-19 16:58 UTC, tmf97 commented on main.py
> +            if (datetime.today() - self.radio.last_telemetry_time).total_seconds() / 60 >= params.TELEM_INTERVAL:
Oh huh, yeah they should be time() values. Also, we add to the downlink queue both in the main loop and in the flight modes - I think we should only do so in the flight modes.

2021-11-01 16:44 UTC, sjz38 commented on flight_modes/low_battery.py
> +        NormalCommandEnum.BasicTelem.value: ([RTC_TIME, ATT_1, ATT_2, ATT_3, ATT_4,
Why are we switching this to `NormalCommandEnum`?

2021-11-01 16:47 UTC, sjz38 commented on telemetry/telemetry.py
> +    def detailed_packet_dict(self) -> Dict[str, Union[int, float]]:
Seems like some changes are becoming out of the scope of the Low battery branch. If there are adjustments that need to be made to telemetry, then we should set up a new branch and add it to Jira

2021-11-01 16:47 UTC, sjz38 approved these changes
Looks good

2021-11-01 17:59 UTC, tmf97 commented on flight_modes/low_battery.py
> +        NormalCommandEnum.BasicTelem.value: ([RTC_TIME, ATT_1, ATT_2, ATT_3, ATT_4,
Ah I was doing a hacky workaround on code that I didn't fully know how it worked (even though I wrote it) to pass the tests

2021-11-01 18:01 UTC, tmf97 commented on telemetry/telemetry.py
> +    def detailed_packet_dict(self) -> Dict[str, Union[int, float]]:
Kinda, but not too far outta scope. For low battery we need a smaller packet to downlink, and this is just that implementation. But yes I'm very guilty of scope creep

2021-11-01 18:02 UTC, merged